homeassistant:
  customize:
    # wall_switch
    switch.wall_switch_left_158d00010e3235:
      friendly_name: 客厅射灯
      icon: mdi:flash
    switch.wall_switch_right_158d00010e3235:
      friendly_name: 客厅吸顶灯
      icon: mdi:ceiling-light
    switch.wall_switch_158d00010b6cc9:
      friendly_name: 次卧吸顶灯
      icon: mdi:ceiling-light
    switch.wall_switch_158d000127a49d:
      friendly_name: 主卧吸顶灯
      icon: mdi:ceiling-light
    switch.wall_switch_left_158d00010ee3fb:
      friendly_name: 洗手间吸顶灯
      icon: mdi:ceiling-light
    switch.wall_switch_right_158d00010ee3fb:
      friendly_name: 洗手间浴霸
      icon: mdi:white-balance-sunny
