homeassistant:
  customize:
    # humidity
    sensor.humidity_158d0001069997:
      friendly_name: 客厅湿度
      icon: mdi:water-percent
    sensor.humidity_158d00010699fe:
      friendly_name: 次卧湿度
      icon: mdi:water-percent
    sensor.humidity_158d00010698f6:
      friendly_name: 主卧湿度
      icon: mdi:water-percent
    sensor.humidity_158d0001150fac:
      friendly_name: 洗手间湿度
      icon: mdi:water-percent
