homeassistant:
  customize:
    # curtain
    cover.curtain_158d00016be84f:
      friendly_name: 主卧窗帘
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      show_last_changed: false
      hide_control: false
      slider_theme:
        min: 0
        max: 100
    cover.curtain_158d00016beccf:
      friendly_name: 客厅窗帘
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      show_last_changed: false
      hide_control: false
      slider_theme:
        min: 0
        max: 100
    cover.curtain_158d00016bed63:
      friendly_name: 次卧窗帘
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      show_last_changed: false
      hide_control: false
      slider_theme:
        min: 0
        max: 100
