homeassistant:
  customize:
    # wall_plug
    switch.wall_plug_158d000159e6b9:
      friendly_name: 热水器插座
      icon: mdi:power-socket
    switch.wall_plug_158d0001574f48:
      friendly_name: 咖啡机插座
      icon: mdi:power-socket
    switch.wall_plug_158d0001574ff4:
      friendly_name: 次卧电暖气插座
      icon: mdi:power-socket
    switch.wall_plug_158d00015751d5:
      friendly_name: 客厅插座
      icon: mdi:power-socket
    switch.wall_plug_158d0001592777:
      friendly_name: 主卧插座
      icon: mdi:power-socket
    switch.wall_plug_158d000159c2e3:
      friendly_name: 阳台插座
      icon: mdi:power-socket
