# Somebody is moving at home
- platform: template
  sensors:
    livingroomtvon:
      value_template: "{{states.media_player.livingroomtv.state == 'on'}}"

    livingrootstaon:
      value_template: "{{states.switch.plug_158d00010ad5d4.state == 'on'}}"