# Somebody is moving at home
- platform: template
  sensors:
    somebodymoving:
      device_class: 'moving'
      value_template: >-
        {%- if is_state("binary_sensor.motion_sensor_158d0000f4164c", "off") and 
            is_state("binary_sensor.motion_sensor_158d0000f418cf", "off") and 
            is_state("binary_sensor.motion_sensor_158d0000f431dd", "off") and 
            is_state("binary_sensor.motion_sensor_158d0000f44617", "off") and 
            is_state("binary_sensor.motion_sensor_158d0001188401", "off") -%}
        false
        {%- else -%}
        true
        {%- endif %}

    livingroomtvon:
      value_template: "{{states.media_player.livingroomtv.state == 'on'}}"

    livingrootstaon:
      value_template: "{{states.switch.plug_158d00010ad5d4.state == 'on'}}"