homeassistant:
  # Name of the location where Home Assistant is running
  name: 郝家
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_location_latitude
  longitude: !secret home_location_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_location_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # overide device name and icon
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  username: !secret mqtt_user
#  password: !secret mqtt_passwd

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_passwd
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

group: !include_dir_merge_named group

# Enable Functions
# Show links to resources in log and frontend
#introduction:
# Enables the frontend
frontend:
# Checks for available updates
updater:
# Discover some devices automatically
# discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
#history:
# View all events in a logbook
#logbook:
# Track the sun
sun:
# enable visiable configurator
config:

# Devices
binary_sensor: !include binary_sensors.yaml
