# yeelight
- platform: yeelight
  devices:
    192.168.1.176:
      name: wc
    192.168.1.240:
      name: lamp

- platform: philips_eyecare
  host: !secret philips_lamp_ip
  name: "bedroomlamp"
  token: !secret philips_lamp_key