- platform: HeWeather
  api_key: !secret heweatherkey
  interval: 300
  isShowWeatherPic: True
  city: haidian
  monitored_conditions:
    # 空气质量指数
    aqi:
      # 空气质量指数
      - aqi
      # PM10
      - pm10
      # PM2.5
      - pm25
      # 空气质量
      - qlty
    # 当天预报
    ToDay_forecast:
      # 日出时间
      - sr
      # 日落时间
      - ss
      # 白天天气情况
      - Weather_d
      # 夜间天气情况
      - Weather_n
      # 相对湿度
      - hum
      # 降水概率
      - pop
      # 最高温度
      - maxTmp
      # 最低温度
      - minTmp
      # 紫外线指数
      - uv
      # 能见度
      - vis
      # 风向
      - dir
      # 风力等级
      - sc
    # 1小时预报
    1Hour_forecast:
      # 天气情况
      - Weather
      # 相对湿度
      - hum
      # 降水概率
      - pop
      # 温度
      - tmp
      # 风向
      - dir
      # 风力等级
      - sc
    # 明天预报
    Tomorrow_forecast:
    # 后天预报
    OfterTomorrow_forecast:

    # 3小时预报
    3Hour_forecast:
    # 6小时预报
    6Hour_forecast:

    # 即时预报
    now:
      # 天气情况
      - Weather
      # 体感温度
      - fl
      # 相对湿度
      - hum
      # 温度
      - tmp
      # 能见度
      - vis
      # 风向
      - dir
      # 风力等级
      - sc
    # 生活指数
    suggestion:
      # 空气指数
      air:
        # 简介
        - brf
        # 数据详情
        - txt
      # 舒适度指数
      comf:
      # 洗车指数
      cw:
      # 穿衣指数
      drsg:
      # 运动指数
      sport:
      # 紫外线指数
      uv:

- platform: template
  sensors:
    current_smart_mi_fan_speed:
      value_template: '{{ states.fan.livingroomfan.attributes.speed_num }}'
    current_smart_mi_fan_shake_head_angle:
      value_template: '{{ states.fan.livingroomfan.attributes.angle }}'

# Synology NAS
#- platform: synologydsm
#  host: !secret nas_ip
#  port: !secret nas_port
#  username: !secret nas_user
#  password: !secret nas_passwd
#  monitored_conditions:
#    - cpu_total_load
#    - memory_real_usage
#    - network_up
#    - network_down
