# weather
- platform: yr
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - windSpeed
    - windDirection
# Synology NAS
- platform: synologydsm
  host: !secret nas_ip
  port: !secret nas_port
  username: !secret nas_user
  password: !secret nas_passwd
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - volume_percentage_used
    - volume_disk_temp_avg