- platform: broadlink
  host: !secret rm_pro_ip
  mac: !secret rm_pro_mac
  switches:
    reciever:
      command_on: ''
      command_off: ''

- platform: chuangmi_ir
  host: !secret chuangmi_ip
  name: "livingroomirremote"
  token: !secret chuangmi_key
  switches:
    reciever:
      command_on: ''
      command_off: ''
    wcfan:
      name: 'wcfan'
      command_on: 'Z6VLAAkCAABpAgAAYgYAAKYIAACJEQAAoSMAAKScAABYeQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBAQEBAQEhISEhISEhIQEBISEBAQEBISEBASEhISFhNXE1AQ=='
      command_off: 'Z6VHAPEBAACBAgAASQYAAIYIAABqEQAAySMAAECcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBAQEBAQEhISEhISEhIQEBASEhAQEBISEhAQEhISFhNQE='
