group:
  bedroom2_lights:
    entities:
      - light.lamp
      - switch.wall_switch_158d00010b6cc9
      - group.ceilinglamp

homeassistant:
  customize:
    group.bedroom2_lights:
      friendly_name: 次卧灯
      icon: mdi:ceiling-light
