light:
  - platform: philips_eyecare
    host: !secret philips_lamp_ip
    name: "bedroomlamp"
    token: !secret philips_lamp_key

homeassistant:
  customize:
    light.bedroomlamp:
      friendly_name: 主卧台灯
      icon: mdi:lamp
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      show_last_changed: false
      hide_control: false
      slider_theme:
        min: 0
        max: 255
