fan:
  - platform: smart_mi_fan
    host: !secret fan_ip
    name: "smartmifan"
    token: !secret fan_key

input_slider:
  smart_mi_fan_speed_slider:
    name: smart_mi_fan_speed_slider
    initial: 0
    min: 0
    max: 100
    step: 1

input_select:
  smart_mi_fan_shake_head_select:
    name: smart_mi_fan_shake_head_select
    options:
      - '0'
      - '30'
      - '60'
      - '90'
      - '120'
    initial: '0'

sensor:
  - platform: template
    sensors:
      current_smart_mi_fan_speed:
        value_template: '{{ states.fan.smartmifan.attributes.speed_num }}'
      current_smart_mi_fan_shake_head_angle:
        value_template: '{{ states.fan.smartmifan.attributes.angle }}'

switch:
  - platform: template
    switches:
      smart_mi_fan_natural_wind_switch:
        value_template: "{{ (states.fan.smartmifan.state == 'on') and (states.fan.smartmifan.attributes.natural_level != 0) }}"
        turn_on:
          service: fan.oscillate
          data:
            entity_id: fan.smartmifan
            oscillating: true
        turn_off:
          service: fan.oscillate
          data:
            entity_id: fan.smartmifan
            oscillating: false

automation:
  - id: smart_mi_fan_speed_slider_control_fan
    alias: smart_mi_fan_speed_slider_control
    trigger:
      - platform: state
        entity_id: input_slider.smart_mi_fan_speed_slider
    action:
      - service: fan.set_speed
        data_template:
          entity_id: fan.smartmifan
          speed: '{{ trigger.to_state.state | int }}'

  - id: smart_mi_fan_speed_sync_with_slider
    alias: smart_mi_fan_speed_sync_with_slider
    trigger:
      - platform: state
        entity_id: sensor.current_smart_mi_fan_speed
    action:
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.smart_mi_fan_speed_slider
          value: '{{ trigger.to_state.state }}'

  - id: smart_mi_fan_shake_head_select_control_fan
    alias: smart_mi_fan_shake_head_select_control_fan
    trigger:
      - platform: state
        entity_id: input_select.smart_mi_fan_shake_head_select
    action:
      - service: fan.set_direction
        data_template:
          entity_id: fan.smartmifan
          direction: '{{ trigger.to_state.state | int }}'

  - id: smart_mi_fan_shake_head_sync_with_select
    alias: smart_mi_fan_shake_head_sync_with_select
    trigger:
      - platform: state
        entity_id: sensor.current_smart_mi_fan_shake_head_angle
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.smart_mi_fan_shake_head_select
          option: '{{ trigger.to_state.state }}'

group:
  SmartMiFan:
    entities:
      - fan.smartmifan
      - input_slider.smart_mi_fan_speed_slider
      - input_select.smart_mi_fan_shake_head_select
      - switch.smart_mi_fan_natural_wind_switch

homeassistant:
  customize:
    fan.smartmifan:
      friendly_name: 智米风扇
    input_slider.smart_mi_fan_speed_slider:
      friendly_name: 风速调节
    input_select.smart_mi_fan_shake_head_select:
      friendly_name: 摇头调节
    switch.smart_mi_fan_natural_wind_switch:
      friendly_name: 自然风开关
      icon: mdi:weather-windy
    group.smartmifan:
      friendly_name: 智米风扇
      icon: mdi:fan

