fan:
  - platform: smart_mi_fan
    host: !secret fan_ip
    name: "smartmifan"
    token: !secret fan_key

input_select:
  smart_mi_fan_shake_head_select:
    name: smart_mi_fan_shake_head_select
    options:
      - '0'
      - '30'
      - '60'
      - '90'
      - '120'
    initial: '0'

sensor:
  - platform: template
    sensors:
      current_smart_mi_fan_shake_head_angle:
        value_template: '{{ states.fan.smartmifan.attributes.angle }}'
      current_smart_mi_fan_battery:
        value_template: '{{ states.fan.smartmifan.attributes.battery }}'

light:
  - platform: template
    lights:
      smart_mi_fan:
        value_template: '{{is_state("fan.smartmifan", "on")}}'
        level_template: >-
          {%- if is_state("fan.smartmifan", "on") -%}
            {{ (states.fan.smartmifan.attributes.speed_num / 100 *255) | int }}
          {%- else -%}
            0
          {%- endif -%}
        turn_on:
          service: fan.turn_on
          data:
            entity_id: fan.smartmifan
        turn_off:
          service: fan.turn_off
          data:
            entity_id: fan.smartmifan
        set_level:
          service: fan.set_speed
          data_template:
            entity_id: fan.smartmifan
            speed: '{{ (brightness / 255 * 100) | int }}'

switch:
  - platform: template
    switches:
      smart_mi_fan_natural_wind_switch:
        value_template: "{{ (states.fan.smartmifan.state == 'on') and (states.fan.smartmifan.attributes.natural_level != 0) }}"
        turn_on:
          service: fan.oscillate
          data:
            entity_id: fan.smartmifan
            oscillating: true
        turn_off:
          service: fan.oscillate
          data:
            entity_id: fan.smartmifan
            oscillating: false

automation:
  - id: smart_mi_fan_shake_head_select_control_fan
    alias: smart_mi_fan_shake_head_select_control_fan
    trigger:
      - platform: state
        entity_id: input_select.smart_mi_fan_shake_head_select
    action:
      - service: fan.set_direction
        data_template:
          entity_id: fan.smartmifan
          direction: '{{ trigger.to_state.state | int }}'

  - id: smart_mi_fan_shake_head_sync_with_select
    alias: smart_mi_fan_shake_head_sync_with_select
    trigger:
      - platform: state
        entity_id: sensor.current_smart_mi_fan_shake_head_angle
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.smart_mi_fan_shake_head_select
          option: '{{ trigger.to_state.state }}'

group:
  SmartMiFan:
    entities:
      - light.smart_mi_fan
      - input_select.smart_mi_fan_shake_head_select
      - switch.smart_mi_fan_natural_wind_switch

homeassistant:
  customize:
    light.smart_mi_fan:
      friendly_name: 智米风扇
      icon: mdi:fan
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      show_last_changed: false
      hide_control: false
      extra_badge:
        entity_id: sensor.current_smart_mi_fan_battery
      slider_theme:
        min: 0
        max: 255

    input_select.smart_mi_fan_shake_head_select:
      friendly_name: 摇头调节
    switch.smart_mi_fan_natural_wind_switch:
      friendly_name: 自然风开关
      icon: mdi:weather-windy
    group.smartmifan:
      friendly_name: 智米风扇
      icon: mdi:fan
    sensor.current_smart_mi_fan_battery:
      friendly_name: 风扇电量
      unit_of_measurement: '%'
