sensor:
  - platform: HeWeather
    api_key: !secret heweatherkey
    interval: 300
    isShowWeatherPic: True
    city: haidian
    monitored_conditions:
      # 空气质量指数
      aqi:
        # 空气质量指数
        - aqi
        # PM10
        - pm10
        # PM2.5
        - pm25
        # 空气质量
        - qlty
      # 当天预报
      ToDay_forecast:
        # 日出时间
        - sr
        # 日落时间
        - ss
        # 白天天气情况
        - Weather_d
        # 夜间天气情况
        - Weather_n
        # 相对湿度
        - hum
        # 降水概率
        - pop
        # 最高温度
        - maxTmp
        # 最低温度
        - minTmp
        # 紫外线指数
        - uv
        # 能见度
        - vis
        # 风向
        - dir
        # 风力等级
        - sc
      # 1小时预报
      1Hour_forecast:
        # 天气情况
        - Weather
        # 相对湿度
        - hum
        # 降水概率
        - pop
        # 温度
        - tmp
        # 风向
        - dir
        # 风力等级
        - sc
      # 明天预报
      Tomorrow_forecast:
      # 后天预报
      OfterTomorrow_forecast:

      # 3小时预报
      3Hour_forecast:
      # 6小时预报
      6Hour_forecast:

      # 即时预报
      now:
        # 天气情况
        - Weather
        # 体感温度
        - fl
        # 相对湿度
        - hum
        # 温度
        - tmp
        # 能见度
        - vis
        # 风向
        - dir
        # 风力等级
        - sc
      # 生活指数
      suggestion:
        # 空气指数
        air:
          # 简介
          - brf
          # 数据详情
          - txt
        # 舒适度指数
        comf:
        # 洗车指数
        cw:
        # 穿衣指数
        drsg:
        # 运动指数
        sport:
        # 紫外线指数
        uv:

group:
  weather_airquality:
    entities:
      - sensor.aqi
      - sensor.aqi_qlty
      - sensor.aqi_pm10
      - sensor.aqi_pm25

  weather_weathernow:
    entities:
      - sensor.now_weather
      - sensor.now_fl
      - sensor.now_hum
      - sensor.now_tmp
      - sensor.now_vis
      - sensor.now_dir
      - sensor.now_sc

  weather_weatherforecast:
    entities:
      - sensor.now_weather
      - sensor.1hour_weather
      - sensor.3hour_weather
      - sensor.6hour_weather
      - sensor.3hour_weather
      - sensor.1hour_weather
      - sensor.oftertomorrowday_weather_day

  weather_todayforecast:
    entities:
      - sensor.today_sr
      - sensor.today_ss
      - sensor.today_weather_day
      - sensor.today_weather_night
      - sensor.today_hum
      - sensor.today_pop
      - sensor.today_mintmp
      - sensor.today_maxtmp
      - sensor.today_uv
      - sensor.today_vis
      - sensor.today_dir
      - sensor.today_sc

  weather_oneHourforecast:
    entities:
      - sensor.1hour_weather
      - sensor.1hour_hum
      - sensor.1hour_pop
      - sensor.1hour_tmp
      - sensor.1hour_dir
      - sensor.1hour_sc

  weather_weathersuggestion:
    entities:
      - sensor.air_suggestion_brf
      - sensor.air_suggestion_txt
      - sensor.comf_suggestion_brf
      - sensor.cw_suggestion_brf
      - sensor.drsg_suggestion_brf
      - sensor.sport_suggestion_brf
      - sensor.uv_suggestion_brf

homeassistant:
  customize:
    sun.sun:
      friendly_name: 昼夜
    sensor.aqi:
      friendly_name: 指数
    sensor.aqi_qlty:
      friendly_name: 质量
    sensor.aqi_pm10:
      friendly_name: PM10
    sensor.aqi_pm25:
      friendly_name: PM2.5
    sensor.now_weather:
      friendly_name: 天气
    sensor.now_fl:
      friendly_name: 体感温度
    sensor.now_hum:
      friendly_name: 湿度
    sensor.now_tmp:
      friendly_name: 温度
    sensor.now_vis:
      friendly_name: 能见度
    sensor.now_dir:
      friendly_name: 风向
    sensor.now_sc:
      friendly_name: 风速
    sensor.3hour_weather:
      friendly_name: 三小时后天气
    sensor.6hour_weather:
      friendly_name: 六小时后天气
    sensor.oftertomorrowday_weather_day:
      friendly_name: 后天天气
    sensor.today_sr:
      friendly_name: 日出时间
    sensor.today_ss:
      friendly_name: 日落时间
    sensor.today_weather_day:
      friendly_name: 白天天气
    sensor.today_weather_night:
      friendly_name: 夜间天气
    sensor.today_hum:
      friendly_name: 湿度
    sensor.today_pop:
      friendly_name: 气压
    sensor.today_mintmp:
      friendly_name: 最低温度
    sensor.today_maxtmp:
      friendly_name: 最高温度
    sensor.today_uv:
      friendly_name: 紫外线指数
    sensor.today_vis:
      friendly_name: 能见度
    sensor.today_dir:
      friendly_name: 风向
    sensor.today_sc:
      friendly_name: 风速
    sensor.1hour_weather:
      friendly_name: 一小时后天气
    sensor.1hour_hum:
      friendly_name: 湿度
    sensor.1hour_pop:
      friendly_name: 气压
    sensor.1hour_tmp:
      friendly_name: 温度
    sensor.1hour_dir:
      friendly_name: 风向
    sensor.1hour_sc:
      friendly_name: 风度
    sensor.air_suggestion_brf:
      friendly_name: 空气指数
    sensor.air_suggestion_txt:
      friendly_name: 空气指数详情
    sensor.comf_suggestion_brf:
      friendly_name: 舒适度
    sensor.cw_suggestion_brf:
      friendly_name: 洗车建议
    sensor.drsg_suggestion_brf:
      friendly_name: 穿衣建议
    sensor.sport_suggestion_brf:
      friendly_name: 运动建议
    sensor.uv_suggestion_brf:
      friendly_name: 紫外线指数
    group.weather_airquality:
      friendly_name: 空气质量
    group.weather_todayforecast:
      friendly_name: 当日天气
    group.weather_weatherforecast:
      friendly_name: 天气预报
    group.weather_weathernow:
      friendly_name: 当前天气
    group.weather_weathersuggestion:
      friendly_name: 建议
    group.weather_onehourforecast:
      friendly_name: 一小时后天气
